### PR TITLE
:new: add workspace configuration

### PR DESCRIPTION
**Pull request by garasubo**
Add Cargo Workspace definition under `src` directory

This will help cargo commands to recognize these packages under this directories and improve developer exeperience.

### CODE REVIEW

**Comment by fukai-t** [comment]
Unfortunately, the build test with your PR have failed. Could you check the result of the test and try to fix it?
https://github.com/RIKEN-RCCS/MilvusVisor/actions/runs/3676166193/jobs/6231681560

**Comment by PG-MANA** [comment]
You should rewrite `.github/workflows/rust.yml`
I think it is OK only to conbine two process: "Build Bootloader" and "Build Kernel" to "Build Hypervisor".

**Comment by garasubo** [comment]
Updated `.github/workflows/rust.yml`. Could you approve running workflows?

**Comment by PG-MANA** [comment]
LGTM, I will modify `.github/workflows/rust.yml` a little after merging.

**Pull request merged**
